name: build
on:
  push:
    branches:
      - master
      - devops_test      
    paths-ignore:
        '.github/**'
  # Triggers the workflow on pull
  pull_request:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-runner]
    env:
      PRODUCT: translation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run and build Hugo
        run: |
          find ./docs-cloud-common/content/ -type d -exec rmdir --ignore-fail-on-non-empty {} \;
          rsync --recursive --delete --force --progress content/${{ env.PRODUCT }} docs-cloud-common/content/
          hugo --source docs-cloud-common --minify --config config.toml,ignore-total-config.toml
